on: push
      
name: Build and Publish Averment
jobs:
  FTP-Deploy-Action:
    name: SFTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Replace <MQTT Password>
      uses: sensuikan1973/replace-deps@v1.1.0
      with:
        extension: "*"
        regex: '{{{MQTT_PASSWORD}}}'
        replacement: ${{ secrets.MQTT_PASSWORD }}

    - name: Replace <PETROLAPI>
      uses: sensuikan1973/replace-deps@v1.1.0
      with:
        extension: "*"
        regex: '{{{PETROLAPI}}}'
        replacement: ${{ secrets.PETROLAPI }}
    
    - name: Replace <ROUTER_USERNAME>
      uses: sensuikan1973/replace-deps@v1.1.0
      with:
        extension: "*"
        regex: '{{{ROUTER_USERNAME}}}'
        replacement: ${{ secrets.ROUTER_USERNAME }} 
    
    - name: Replace <ROUTER_PASSWORD>
      uses: sensuikan1973/replace-deps@v1.1.0
      with:
        extension: "*"
        regex: '{{{ROUTER_PASSWORD}}}'
        replacement: ${{ secrets.ROUTER_PASSWORD }} 
    
    - name: Replace <INFLUXDB_KEYGEN>
      uses: sensuikan1973/replace-deps@v1.1.0
      with:
        extension: "*"
        regex: '{{{INFLUXDB_KEYGEN}}}'
        replacement: ${{ secrets.INFLUXDB_KEYGEN }}

    - name: SFTP-Deploy <anna-sys>
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 2200
        localDir: AnnA-Sys/Apps/
        remoteDir: /home/data/Apps
        git-ftp-args: --insecure
      
    - name: SFTP-Deploy <anna-garage>
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 2201
        localDir: AnnA-Garage/Apps/
        remoteDir: /home/data/Apps
        git-ftp-args: --insecure

    - name: SFTP-Deploy <anna-solar>
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 2202
        localDir: AnnA-Solar/Apps/
        remoteDir: /home/data/Apps
        git-ftp-args: --insecure
    
    - name: SFTP-Deploy <anna-oh>
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: 2299
        localDir: Docker/OpenHab/
        remoteDir: /docker/openhab/conf
        git-ftp-args: --insecure
